### ISSUE TITLE
[Bug] Obsidian can be mined with non-diamond tools

### ISSUE THREAD

**Issue by alexpostovskiy** [gnembon/carpet-extra#112] opened 2020-07-28 03:48 UTC
Obsidian can be mined with all non-diamond tools, including by hand, in 1.16.1 / carpet-extra 1.4.0. This does not seemingly apply to other blocks, such as diamond ore with a wooden pickaxe. This is present with all carpet-extra features on default, but is not present when the mob is removed.

**Comment by javiersalcedo** [comment] 2020-08-06 16:53
Came here to post this. Obsidian is also mined faster (about 3x) that the wiki says it should be destroyed by each tool bellow diamond level.

**Comment by altrisi** [comment] 2020-08-12 15:16
This is caused by a change in vanilla code in 1.16 for block registrations, that kind-of conflicts with the renewableLava Mixin.

**Comment by altrisi** [comment] 2020-09-09 19:38
Fixed in #115 @ 3544257
For some reason it didn't autoclose the issue.
It can be closed now.

**Closed** 2020-09-23 03:42 UTC
