### ISSUE TITLE
[Feature Request]Implement Per-player Mob Spawning

### ISSUE THREAD

**Issue by Neubulae** [gnembon/carpet-extra#152] opened 2020-11-08 11:09 UTC
Which is basically https://github.com/LambdaCraft/fabric-per-player-spawns and the Paperspigot patch
I thought this could be a nice addition to carpet extra.

**Comment by altrisi** [comment] 2020-11-08 12:30
Duplicate of gnembon/fabric-carpet#528.

Also, if it is already available as another mod, why would you want to add it in carpet too?

**Comment by Neubulae** [comment] 2020-11-10 10:38
> Duplicate of [gnembon/fabric-carpet#528](https://github.com/gnembon/fabric-carpet/issues/528).
> 
> Also, if it is already available as another mod, why would you add it in carpet too?

As it's not ported and seemingly abandoned as nobody responds to the issue for months.

And also this fits quite nice in Carpet-Extra I guess?

**Comment by Ghoulboy78** [comment] 2020-11-29 14:06
But there is the same problem I mentioned in the previous issue. That is, that is messes up with the existing mobcap system in the game, making a number of technical things effectively useless.

**Comment by altrisi** [comment] 2021-07-17 20:29
Note that the mod you mentioned has been updated in https://github.com/vlad2305m/fabric-per-player-spawns

**Comment by Neubulae** [comment] 2021-07-17 23:57
I forgot to close this issue. dang

**Closed** 2021-07-17 23:57 UTC
