### ISSUE TITLE
[Bug] AutoCraftingDropper and interaction with hoppers

### ISSUE THREAD

**Issue by samolego** [gnembon/carpet-extra#68] opened 2020-03-11 09:31 UTC
Hi!

I'm experiencing an issue with `autoCraftingDropper` feature.

Expected behaviour:
As far as I know, hoppers, facing into autoCraftingDropper should input one item per slot.

What's actually happening:
Hoppers insert items normally (vanilla style).

Carpet version: 1.15.2-1.3.13
Carpet Extra version: 1.15.2-1.3.13+v200304

Fabric API version: 0.5.0+build.293-1.15

Items in hopper
![2020-03-11_10 16 43](https://user-images.githubusercontent.com/34912839/76401945-fbd28e80-6382-11ea-8d1d-866936892939.png)

Items in autoCraftingDropper:
![2020-03-11_10 17 06](https://user-images.githubusercontent.com/34912839/76401940-faa16180-6382-11ea-9795-22ab602b305c.png)

**Comment by DeadlyMC** [comment] 2020-03-15 13:52
![2020-03-15_19 20 40](https://user-images.githubusercontent.com/43000902/76702728-29f0ff00-66f2-11ea-974b-f3ad67aaba4e.png)
Weird, i just tested the feature and it did work. Did you check if you have enabled the carpet rule?
Maybe you could share a wdl or a better pic showing your setup too

**Comment by Neubulae** [comment] 2020-03-17 09:10
Experiencing the same thing too, maybe that's a result of mod conflict? Can you provide a mod list?

**Comment by Neubulae** [comment] 2020-03-17 09:19
Do you have NBT-Crafting installed?

**Comment by samolego** [comment] 2020-03-17 12:07
No, I don't have NBT crafting present.

I've also made sure that feature is turned on :-).

Here's a list of my mods. Might be hopper optimizations?
![Screenshot_20200317-130607_MiXplorer](https://user-images.githubusercontent.com/34912839/76854920-499e3980-6850-11ea-8bb6-2f65251db643.png)

**Comment by Neubulae** [comment] 2020-03-17 12:08
> No, I don't have NBT crafting present.
> 
> I've also made sure that feature is turned on :-).
> 
> Here's a list of my mods. Might be hopper optimizations?
> ![Screenshot_20200317-130607_MiXplorer](https://user-images.githubusercontent.com/34912839/76854920-499e3980-6850-11ea-8bb6-2f65251db643.png)

It could be, as hopperOpti is also present on my side

**Comment by Neubulae** [comment] 2020-03-17 12:09
how about removing it and see?

**Comment by Neubulae** [comment] 2020-03-17 12:14
> No, I don't have NBT crafting present.
> 
> I've also made sure that feature is turned on :-).
> 
> Here's a list of my mods. Might be hopper optimizations?

Found the problem, it's a problem with optimizedInventories, are there any newer versions of hopperOpti?

**Comment by samolego** [comment] 2020-03-17 12:32
Yup, there's one, but it still doesn't seem to be working ... :-(

**Comment by Neubulae** [comment] 2020-03-17 13:33
> Yup, there's one, but it still doesn't seem to be working ... :-(

I reported the bug on hopperOptimization's side, they're fixing it xD

**Comment by samolego** [comment] 2020-03-17 15:05
Should we close this here then?

**Comment by 2No2Name** [comment] 2020-03-17 16:08
Don't close this. As the author of hopperOptimizations I found that the problem is that carpet-extra uses isValidInvStack to make hoppers not insert items when there is already 1 item in the same slot of the autocrafting dropper. Therefore it will return false, when the stack is valid, but the slot already has an item. The correct solution would be to implement SidedInventory::canInsertInvStack instead. Working around this with hopperoptimizations is kind of hard, as the only way to detect that is to call it every time, or get a specialized solution for carpet-extra.

**Comment by samolego** [comment] 2020-03-23 12:34
Latest release of hopper optimizations fixes this issue.

**Comment by Megaminx12** [comment] 2020-10-10 15:37
@2No2Name Why shouldn't OP close this?

**Comment by 2No2Name** [comment] 2020-10-10 15:47
Oh that is very outdated info. I was talking to gnembon on discord and I decided to fix it on my side. 

This can be closed

**Closed** 2020-10-10 18:17 UTC
