### ISSUE TITLE
Barrels and Bee Nests Dissappearing

### ISSUE THREAD

**Issue by MatthewOverall** [gnembon/carpet-extra#40] opened 2019-12-11 00:15 UTC
It appears that while having carpet-extra mod for 1.15 installed, some blocks randomly disappear and cannot be interacted with. Removing the mod restores the blocks.

**Comment by gnembon** [comment] 2019-12-13 19:13
What is your setup. Is carpet the only mod you have? do you use fabric-api? is it single-player or client-server and what mods are on the client in this case?

**Comment by LimeTheOn** [comment] 2019-12-16 20:48
Can confirm, in our case we have carpet and carpet extra. We did a fresh install of 1.15 fabric with just your mods. Ive been testing for the past hour and having only fabric without your mods doesn't (or in my case didn't) reproduce the rendering issue he is trying to explain here. Every new tile entity(I guess) that was added in 1.14 or 15 smokers,blast furnaces,stone cutters, bees nests, grind stones appear to not render at all and sometimes in weird edge cases render as other blocks  as mentioned here https://github.com/FabricMC/fabric/issues/458 by flori-schwa at the bottom of the issue.
It doesn't matter if we join with a vanilla or a fabric client they don't even reappear when re-joining the server or reloading the chunks/textures(I mean f3+t or a). My best guess is that its a chunk unloading and the server forgetting the send info about the block being there but its weird...if I 'place' another block(like dirt for example) in place of these blocks then I can access it again since I can click on it but it wont reappear as it itself rather stay as dirt even after re-joining...I don't know :D
I've tried moving it with pistons....does nothing other then moves it ofc but it stays invisible.
You could already guess we have moveable tile entites set to true. Sorry for the light novel just tried to give as much info as I could. Thanks for carpet tho we are loving it! <3

I'm currently testing if this is the same in 1.15.1

**Comment by gnembon** [comment] 2019-12-18 12:50
Yeah, please confirm you are on version 1.3.0 and you see these issues. I know it was the case in the last 1.2.x

**Comment by LimeTheOn** [comment] 2019-12-18 17:54
We were getting these in 1.2.6 I know that for sure since 1.3.x wasn't even out when we started the server up for the first time. I'm at work now so cant test stuff atm. So bare with me im kinda slow but we don't have to match carpet and carpet extras version numbers simply update carpet and it fixes it? Im asking because I haven't seen carpet extra 1.3.x on curseforge.

**Comment by LimeTheOn** [comment] 2019-12-21 04:24
We updated the server to 1.3 and everything is back to normal. If people report the said blocks being other blocks instead of invisible... like half of a door or a bed its that they have 1.3 clientside but their server is still 1.2
Thank you!

**Closed** 2019-12-28 22:03 UTC
