### ISSUE TITLE
[Suggestion] Remove fillLimit limit of 20M

### ISSUE THREAD

**Issue by StereoMadnessss** [gnembon/carpet-extra#257] opened 2022-04-18 17:59 UTC
I just find it annoying that the 20M fill limit exists. I know it is for safety but this is an extras mod and also it accepts numbers up to 2147483647 in the command. For some reason though it doesn't set the value up correctly and since it accepts it, it should be a valid fillLimit number.

**Comment by StereoMadnessss** [comment] 2022-04-18 18:03
https://user-images.githubusercontent.com/77188051/163852626-4c923c3d-1971-4937-9fca-e71428ac947e.mov

It accepts 2147483647 but not 2147483648 so it would be reasonable to let it go this far.

**Comment by StereoMadnessss** [comment] 2022-04-18 18:04
2147483647 gives you a "Too large fillLimit" message but 2147483648 gives you an error to show that it uses Int tags and that it can go that far

**Comment by altrisi** [comment] 2022-04-19 20:48
`fillLimit` is from base carpet, not extra, so the issue should be there.

And in there, this is a duplicate of gnembon/fabric-carpet#858. Feel free to comment there!

The unexpected error one with out of bounds numbers (and any other input really) is known and there is a fix in a PR just pending reviews.

**Closed by altrisi** 2022-04-19 20:48 UTC
